apiVersion: v1
kind: Service
metadata:
  name: p-wordpress-deployment
  namespace: production
  labels:
    app: p-wordpress-deployment
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: p-wordpress-deployment
