apiVersion: v1
kind: Service
metadata:
  name: s-lp-deployment
  namespace: staging
  labels:
    app: s-lp-deployment
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: s-lp-deployment
