apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-pesbuk-deployment
  namespace: production
  labels:
    app: p-pesbuk-deployment
    env: production
spec:
  selector:
    matchLabels:
      app: p-pesbuk-deployment
      env: production
  replicas: 2
  template:
    metadata:
      labels:
        app: p-pesbuk-deployment
        env: production
    spec:
      containers:
      - name: p-pesbuk-deployment
        image: pujakesuma/pesbuk-secret:1.0
        ports:
        - containerPort: 80
        env:  
            - name: DB_HOST    
              value: "database-1.cogsyqawtx3c.us-east-2.rds.amazonaws.com"
            - name: DB_USER    
              valueFrom:       
                secretKeyRef:
                  name: p-secret-fb
                  key: DB_USER  
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: p-secret-fb
                  key: DB_PASS
